<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Dusiburg.AI.O2C.ServiceDefaults\Dusiburg.AI.O2C.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Dusiburg.AI.O2C.Crm.Data\Dusiburg.AI.O2C.Crm.Data.csproj" />
  </ItemGroup>

</Project>
