<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>34bc01f3-9054-44c3-943c-06c5b46a1f88</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Erp.Api\Erp.Api.csproj" />
    <ProjectReference Include="..\Erp.Mcp\Erp.Mcp.csproj" />
    <ProjectReference Include="..\Crm.Mcp\Crm.Mcp.csproj" />
    <ProjectReference Include="..\Orchestrator\Orchestrator.csproj" />
    <ProjectReference Include="..\Approvals.Web\Approvals.Web.csproj" />
  </ItemGroup>

</Project>
